# Generated by Django 6.0.6 on 2026-07-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_aiinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
