# Generated by Django 6.0.6 on 2026-07-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_first_name_application_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterview',
            name='answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiinterview',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
