# Generated by Django 6.0.6 on 2026-09-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_aiinterview_answers_aiinterview_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterview',
            name='is_generating',
            field=models.BooleanField(default=False),
        ),
    ]
