# Generated by Django 6.0.6 on 2026-09-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_aiinterview_is_generating'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterview',
            name='is_evaluating',
            field=models.BooleanField(default=False),
        ),
    ]
