# Generated by Django 6.0.6 on 2026-07-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Entry Level', 'Entry'), ('Mid Level', 'Mid'), ('Senior Level', 'Senior')], max_length=20),
        ),
    ]
