# Generated by Django 6.0.6 on 2026-08-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminuser_applicantuser_recruiteruser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Recruiter', 'Recruiter'), ('Applicant', 'Applicant')], default='Applicant', max_length=20),
        ),
    ]
