# Generated by Django 6.0.6 on 2026-08-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECRUITER', 'Recruiter'), ('APPLICANT', 'Applicant')], default='APPLICANT', max_length=20),
        ),
    ]
