# Generated by Django 6.0.6 on 2026-07-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Free', 'Free'), ('3 Months', 'Three Months'), ('6 Months', 'Six Months'), ('1 Year', 'One Year'), ('Lifetime', 'Lifetime')], max_length=20, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text="Leave blank for Free/Lifetime - they don't expire on a fixed date.", null=True)),
                ('vacancy_limit', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited vacancies.', null=True)),
            ],
            options={
                'db_table': 'subscription_plan',
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Paused', 'Paused'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='companies.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.companyplan')),
            ],
            options={
                'db_table': 'company_subscription',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidx', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='khalti', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.companysubscription')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
